version: '3'
services:
  servidor:
    build: 
      context: .
      dockerfile: "Dockerfile-servidor"
    ports: 
      - "9090:5000"
  
  cliente:
    build:
      context: .
      dockerfile: "Dockerfile-cliente"
    ports: 
      - "8080:80"
  

      
    
    
