version: '3'
services:
  servidor:
    build: .
    ports: 
      - "9090:5000"
  
  cliente:
    image: nginx
    volumes: 
      - ./frontend:/usr/share/nginx/html
    ports: 
      - "8080:80"
  

      
    
    
