version: '3'
services:
  servidor:
    build: .
    ports: 
      - "9090:5000"
  
  cliente:
    image: nginx
    build:
      context: .
      dockerfile: "Dockerfile-front"
    ports: 
      - "8080:80"
  

      
    
    
