version: '3'
services:
  servidor:
    build: 
      context: .
      dockerfile: "Dockerfile-servidor"
    ports: 
      - "9090:5000"
    networks:
      - rede_interna
  
  cliente:
    build:
      context: .
      dockerfile: "Dockerfile-cliente"
    ports: 
      - "80:80"
    networks:
      - rede_interna
networks:
  rede_interna:
    driver:  bridge  

      
    
    
